version: '3'

services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo-app:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    environment:
       VIRTUAL_HOST: matomo.wingcom.local

  matomodb:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - matomodb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=matomo
    env_file:
      - ./matomodb.env

  matomo-app:
    depends_on:
     - matomodb
    image: matomo:fpm-alpine
    restart: always
    links:
      - matomodb
    volumes:
#      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
      - matomo-app:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=matomodb
    env_file:
      - ./matomodb.env
    restart: always

volumes:
  matomodb:
  matomo-app:

networks:
  default:
    external:
      name: nginx-reverseproxy
